CREATE TABLE algorithms(
algorithm_id VARCHAR2(50) PRIMARY KEY,
algorithm_name VARCHAR2(200)
);

DROP TABLE algorithms;

CREATE TABLE parameters(
parameter_id VARCHAR2(50) PRIMARY KEY,
algorithm_id VARCHAR2(50),
turn_time NUMBER,
e_greedy NUMBER,
c NUMBER,
sim_depth NUMBER,
playout_number NUMBER
);

ALTER TABLE parameters ADD
CONSTRAINT fk_algorithm_id FOREIGN KEY (algorithm_id) REFERENCES algorithms(algorithm_id);

CREATE TABLE simulations(
sim_id NUMBER GENERATED by default on null as IDENTITY,
outcome VARCHAR2(50),
red_player VARCHAR2(50),
blue_player VARCHAR2(50),
turn_cnt NUMBER
);

ALTER TABLE simulations ADD 
CONSTRAINT pk_sim_id PRIMARY KEY (sim_id);
  
//select count(*) from simulations s join performances p on s.sim_id=p.sim_id where p.parameter_id='MCTS_PW__d';
CREATE TABLE performances(
performance_id NUMBER GENERATED by default on null as IDENTITY,
sim_id NUMBER,
parameter_id VARCHAR2(50),
atk_cnt_first5 NUMBER,
atk_cnt_second5 NUMBER,
atk_cnt NUMBER,
move_cnt NUMBER,
rem_hp NUMBER
);

ALTER TABLE performances ADD 
CONSTRAINT pk_performance_id PRIMARY KEY (performance_id);

//drop table simulations;
//drop table performances;

ALTER TABLE simulations ADD
CONSTRAINT fk_red_player_id FOREIGN KEY (red_player) REFERENCES parameters(parameter_id);
ALTER TABLE simulations ADD
CONSTRAINT fk_blue_player_id FOREIGN KEY (blue_player) REFERENCES parameters(parameter_id);


ALTER TABLE performances ADD
CONSTRAINT fk_parameter_id FOREIGN KEY (parameter_id) REFERENCES parameters(parameter_id);
ALTER TABLE performances ADD
CONSTRAINT fk_sim_id FOREIGN KEY (sim_id) REFERENCES simulations(sim_id);

CREATE SEQUENCE sim_seq START WITH 1 INCREMENT BY 1 NOMAXVALUE;

CREATE SEQUENCE performance_seq START WITH 1 INCREMENT BY 1 NOMAXVALUE;

CREATE or replace TRIGGER sim_id
  BEFORE INSERT ON simulations
  FOR EACH ROW
BEGIN
  :NEW.sim_id := sim_seq.NEXTVAL;
END;

CREATE or replace TRIGGER performance_id
  BEFORE INSERT ON performances
  FOR EACH ROW
BEGIN
  :NEW.performance_id := performance_seq.NEXTVAL;
END;



INSERT INTO algorithms VALUES ('MCTS', 'Monte Carlo Tree Search');
INSERT INTO algorithms VALUES ('DLMC', 'Depth Limited Monte Carlo');
INSERT INTO algorithms VALUES ('MCTS_BB', 'Monte Carlo Tree Search Bridge Burning');
INSERT INTO algorithms VALUES ('MCTS_PW', 'Monte Carlo Tree Search Progressive Widening');
INSERT INTO algorithms VALUES ('AAS', 'Attack Action Search');
INSERT INTO parameters (parameter_id, algorithm_id) values ('asdas2da2w', 'MCTS');
INSERT INTO simulations (outcome, red_player, blue_player, turn_cnt) values ('draw', 'asdas2da2w', 'asdas2da2w', 20);
delete from parameters;
